# Generated by Django 2.2.3 on 2019-07-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('pdf', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=100)),
                ('c_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
