# Generated by Django 2.2.3 on 2019-07-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, default=True, max_length=5, null=True),
        ),
    ]
