# Generated by Django 2.2.3 on 2019-07-31 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190724_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='type',
            new_name='user_type',
        ),
    ]
