# Generated by Django 2.2.3 on 2019-07-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190731_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
